version: '3.8'

services:
  web:
    build: .
    container_name: nextjs_bun_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: pg_my_blog
    environment:
      POSTGRES_USER: manu
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: my_blog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
